version: 2
updates:
- package-ecosystem: npm
  directory: "/angular2-quickstart-systemjs"
  schedule:
    interval: daily
    time: "09:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 15.0.0
  - dependency-name: concurrently
    versions:
    - 6.0.0
    - 6.0.1
  - dependency-name: "@angular/platform-browser-dynamic"
    versions:
    - 11.1.1
    - 11.1.2
    - 11.2.0
    - 11.2.1
    - 11.2.2
    - 11.2.3
    - 11.2.4
  - dependency-name: "@angular/compiler"
    versions:
    - 11.1.1
    - 11.1.2
    - 11.2.0
    - 11.2.1
    - 11.2.2
    - 11.2.3
  - dependency-name: "@angular/upgrade"
    versions:
    - 11.1.1
    - 11.1.2
    - 11.2.0
    - 11.2.1
    - 11.2.2
    - 11.2.3
  - dependency-name: "@angular/platform-browser"
    versions:
    - 11.1.1
    - 11.1.2
    - 11.2.0
    - 11.2.1
    - 11.2.2
    - 11.2.3
  - dependency-name: "@angular/router"
    versions:
    - 11.2.2
    - 11.2.3
